name: demo file

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a one-line script
      run: echo "Hello, World!"
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run a one-line script
      run: echo "Deploying to production..."

    - name: Docker login
      run: |
        docker login ${{secrets.Harbor_URL}} \
        -u ${{secrets.Harbor_USERNAME}} \
        -p ${{secrets.Harbor_PASSWORD}}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{secrets.Harbor_URL}}/demo/myapp:${{ github.sha }} .
        docker push ${{secrets.Harbor_URL}}/demo/myapp:${{ github.sha }}